### ISSUE TITLE
Modify UI in Lobby page

### ISSUE THREAD

**Issue by Haaaan1** [sopra-fs24-group-09/sopra-fs24-group-09-client#107]

**Comment by Haaaan1** [comment]
Modify user profile popup UI

**Comment by Haaaan1** [comment]
Enhance game rule button

**Comment by Haaaan1** [comment]
Change guide position and automatic popup when first enter lobby

**Comment by Haaaan1** [comment]
Add notify for user to allow using microphone

**Comment by Haaaan1** [comment]
<img width="475" alt="image" src="https://github.com/sopra-fs24-group-09/sopra-fs24-group-09-client/assets/114866543/eabcb5c2-eca4-4f51-9c41-fd0e1a8b5137">
Modified number input in room creation

**Comment by Haaaan1** [comment]
<img width="622" alt="image" src="https://github.com/sopra-fs24-group-09/sopra-fs24-group-09-client/assets/114866543/1f0b0ee0-a251-48f3-82b4-f63c6bc956b9">
Change room empty place remaining display and cursor on the "plus" icon

**Comment by petertheprocess** [comment]
![image](https://github.com/sopra-fs24-group-09/sopra-fs24-group-09-client/assets/30321432/377a7ad5-f4e2-4cd2-8f69-0b95a5079de0)
