### ISSUE TITLE
Display room capacity and how much empty seats left

### ISSUE THREAD

**Issue by Haaaan1** [sopra-fs24-group-09/sopra-fs24-group-09-client#141]

**Comment by petertheprocess** [comment]
Follow this figma UI
![image](https://github.com/sopra-fs24-group-09/sopra-fs24-group-09-client/assets/30321432/920b4459-16c3-469b-83b5-e217c60c227a)

**Comment by petertheprocess** [comment]
![image](https://github.com/sopra-fs24-group-09/sopra-fs24-group-09-client/assets/30321432/e491b0fb-6e0d-4602-a657-3513b65719c2)

Now the status bar is using the same color rather than a different color for each state.

**Comment by Haaaan1** [comment]
<img width="634" alt="image" src="https://github.com/sopra-fs24-group-09/sopra-fs24-group-09-client/assets/114866543/0b6d8e54-ef07-4caa-afcf-c605f6cdaa3d">
Both have been fixed @petertheprocess

**Comment by petertheprocess** [comment]
Fix the size of avatar box c4026c9df7cdc9c39a713c3a203c0e043000ff66
## before
![image](https://github.com/sopra-fs24-group-09/sopra-fs24-group-09-client/assets/30321432/2688edaf-2a70-4585-ada9-d7e14319fa3e)
## after
![image](https://github.com/sopra-fs24-group-09/sopra-fs24-group-09-client/assets/30321432/e8e0502f-8279-4903-ad63-b2ce669221ee)
