### ISSUE TITLE
Create Login and Register forms

### ISSUE THREAD

**Issue by Zehao-Zhang** [sopra-fs24-group-09/sopra-fs24-group-09-client#20]

**Comment by petertheprocess** [comment]
Mockup UI:
![image](https://github.com/sopra-fs24-group-09/sopra-fs24-group-09-client/assets/30321432/2b666a50-36bb-47e9-ab6b-7858d8b52def)

![image](https://github.com/sopra-fs24-group-09/sopra-fs24-group-09-client/assets/30321432/eedf67bb-ea19-43bb-a83d-9c93f523696e)
