### ISSUE TITLE
After login / registration, the player is redirected to Lobby page (design Lobby page)

### ISSUE THREAD

**Issue by Zehao-Zhang** [sopra-fs24-group-09/sopra-fs24-group-09-client#29]

**Comment by petertheprocess** [comment]
![image](https://github.com/sopra-fs24-group-09/sopra-fs24-group-09-client/assets/30321432/1892af6a-c947-4969-9207-e89642ca2a3e)
The mock avaters are not showing.

**Comment by Haaaan1** [comment]
The avatar showing bug has been fixed.
<img width="1460" alt="image" src="https://github.com/sopra-fs24-group-09/sopra-fs24-group-09-client/assets/114866543/4c32e33f-b57b-47eb-9342-f6c314622bb0">
